### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by montyly**
TODO: add code owners for
- `/development-guidelines/`
- `/learn_evm/`
- `/not-so-smart-contracts/algorand/`
- `/not-so-smart-contracts/cairo/`
- `/not-so-smart-contracts/cosmos/`
- `/not-so-smart-contracts/substrate/`
- `/not-so-smart-contracts/solana/`
- `/program-analysis/echidna`
- `/program-analysis/slither`

### CODE REVIEW

**Comment by ggrieco-tob** [comment]
I can own `program-analysis/echidna`

**Comment by GrosQuildu** [comment]
Can help with `/not-so-smart-contracts/cosmos/`

**Comment by 0xicingdeath** [comment]
Can help with `/development-guidelines` and `/not-so-smart-contracts/substrate`

**Comment by bohendo** [comment]
I can take `/learn_evm/` but it's pretty lean & there's not much there to keep an eye on.
Would it be worth building it out & adding more evm learning materials? eg yellow paper notes, differences between various EVM implementations, misc EVM edge cases, something else?

**Comment by montyly** [comment]
@bohendo YES, see
- https://github.com/crytic/building-secure-contracts/pull/191
- https://github.com/crytic/building-secure-contracts/pull/185
- https://github.com/crytic/building-secure-contracts/issues/121

**Comment by bohendo** [comment]
@montyly awesome, I'll spend some time tomorrow resolving/polishing those 3 issues/PRs 😁 👍
I already have some [personal yellow paper notes](https://github.com/bohendo/evm-notes) that I could revamp into something useful for the rest of the community

**Comment by technovision99** [comment]
I can help with `not-so-smart-contracts/cairo/`

**Comment by S3v3ru5** [comment]
I can help with `/not-so-smart-contracts/algorand/`

**Pull request merged**
